<a href="https://colab.research.google.com/github/ammad19/AI-course-exercises/blob/master/Assignment_For_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [9]:
data1 = [0,0,0,0,0,0,0,0,0,0]
arr1 = np.array(data1)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr2 = np.zeros(10)

In [11]:
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr3 = np.arange(10,51,1)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
arr3.shape

(41,)

In [14]:
arr3.dtype

dtype('int64')

In [15]:
arr3.ndim

1

In [16]:
np.__version__

'1.19.4'

In [17]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [18]:
arr4 = np.array([True,True,True])
arr4

array([ True,  True,  True])

In [19]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr5 = np.array(data2)
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
data3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr6 = np.array(data3)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr7 = np.arange(10)
arr7[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
arr6[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [23]:
arr8 = np.zeros(10)
arr8[5] = 1
arr8

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [24]:
arr9 = np.identity(3)
arr9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr10 = np.array([1, 2, 3, 4, 5], dtype=float)
arr10

array([1., 2., 3., 4., 5.])

In [26]:
arr10.dtype

dtype('float64')

In [27]:
arr11 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr12 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr11*arr12

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [28]:
arr11==arr12

array([[False, False, False],
       [False, False, False]])

In [30]:
arr6[arr6 % 2 == 1]


array([ 1,  3,  5,  7,  9, 11])

In [37]:
arr6 = np.full(6,-1,int)

In [38]:
arr6

array([-1, -1, -1, -1, -1, -1])