<a href="https://colab.research.google.com/github/ammad19/AI-course-exercises/blob/master/Assignment_For_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
data1 = [0,0,0,0,0,0,0,0,0,0]
arr1 = np.array(data1)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
arr2 = np.zeros(10)

In [5]:
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr3 = np.arange(10,51,1)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [11]:
arr3.shape

(41,)