<a href="https://colab.research.google.com/github/ammad19/AI-course-exercises/blob/master/Assignment1_For_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
data1 = [0,0,0,0,0,0,0,0,0,0]
arr1 = np.array(data1)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
arr2 = np.zeros(10)

In [5]:
arr2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr3 = np.arange(10,51,1)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
arr3.shape

(41,)

In [8]:
arr3.dtype

dtype('int64')

In [9]:
arr3.ndim

1

In [10]:
np.__version__

'1.19.4'

In [11]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [12]:
arr4 = np.array([True,True,True])
arr4

array([ True,  True,  True])

In [13]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr5 = np.array(data2)
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
data3 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr6 = np.array(data3)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr7 = np.arange(10)
arr7[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
arr6[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [17]:
arr8 = np.zeros(10)
arr8[5] = 1
arr8

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [18]:
arr9 = np.identity(3)
arr9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
arr10 = np.array([1, 2, 3, 4, 5], dtype=float)
arr10

array([1., 2., 3., 4., 5.])

In [20]:
arr10.dtype

dtype('float64')

In [21]:
arr11 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr12 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr11*arr12

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [22]:
arr11==arr12

array([[False, False, False],
       [False, False, False]])

In [23]:
arr6[arr6 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [24]:
arr6 = np.full(6,-1,int)

In [25]:
arr6

array([-1, -1, -1, -1, -1, -1])

In [26]:
arr13 = np.arange(10)

In [27]:
arr13[5:9] = 12

In [28]:
arr13

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [29]:
arr2d = np.array([[1,0,1],[1,0,1]])

In [30]:
arr2d

array([[1, 0, 1],
       [1, 0, 1]])

In [31]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])


In [32]:
arr2d[1][1] = 12

In [33]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [34]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64

In [35]:
arr3d[0]

array([[64, 64, 64],
       [64, 64, 64]])

In [36]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[:1]

array([[1, 2, 3]])

In [37]:
arr2d[1,:2][1]

5

In [38]:
arr2d[:2,2]

array([3, 6])

In [39]:
arr2d = np.random.random((10,10))

In [40]:
arr2d

array([[0.01290911, 0.22070914, 0.96833955, 0.37234688, 0.20193962,
        0.10696997, 0.00654338, 0.95279147, 0.1172928 , 0.07022562],
       [0.70433389, 0.04682904, 0.80367973, 0.19036664, 0.50968992,
        0.96135413, 0.59438304, 0.79634263, 0.68511212, 0.68757896],
       [0.51384067, 0.94434162, 0.10391217, 0.11102742, 0.1632335 ,
        0.10758969, 0.84838832, 0.98357727, 0.18189613, 0.66945499],
       [0.4445125 , 0.97106543, 0.86452923, 0.51079045, 0.8758639 ,
        0.78676016, 0.94937542, 0.7527376 , 0.21740071, 0.94831613],
       [0.41841529, 0.92838916, 0.43133006, 0.90336986, 0.78228505,
        0.72969355, 0.44332072, 0.16419793, 0.16834742, 0.40913226],
       [0.82362221, 0.44263148, 0.31716706, 0.39124893, 0.23887505,
        0.37193285, 0.68036238, 0.85954178, 0.55130498, 0.02172065],
       [0.09615947, 0.0401916 , 0.82303693, 0.69010564, 0.70643843,
        0.28418924, 0.18343707, 0.41900523, 0.74958648, 0.32365034],
       [0.12665052, 0.3866172 , 0.2673048

In [41]:
arr2d.min()

0.006543381320792796

In [42]:
arr2d.max()

0.9835772744029562

In [43]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [44]:
np.where(a==b)

(array([1, 3, 5, 7]),)

In [45]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [46]:
data

array([[ 1.75345516, -0.60475084,  0.15747855,  0.59432818],
       [-1.60455341, -0.82627781,  0.58714719, -1.39945772],
       [ 0.33355011, -0.74959599, -0.7524754 ,  1.0001302 ],
       [ 1.87530309, -0.76140863,  1.59634562, -0.63622075],
       [-1.17468258,  0.69136837, -0.84619378, -1.08482836],
       [-1.02293512,  1.02475554,  0.31646736, -0.60882152],
       [ 1.36075877,  0.36960376,  0.22826417, -0.07478187]])

In [47]:
mask = (names!='Joe') & (names!='Will')

In [48]:
data[mask]

array([[ 1.75345516, -0.60475084,  0.15747855,  0.59432818],
       [ 1.87530309, -0.76140863,  1.59634562, -0.63622075]])

In [49]:
arr2d1 = np.arange(1,16).reshape(5,3)

In [50]:
arr2d1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [51]:
arr2d2 = np.arange(1,17).reshape(2,2,4)
arr2d2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [52]:
np.swapaxes(arr2d2,1,0)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

In [53]:
arr14 = np.arange(1,11)
arr14

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr15 = np.sqrt(arr14)

In [55]:
arr15[arr15<0.5] = 0

In [56]:
arr15

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [57]:
a = np.random.randn(12)

In [58]:
a

array([-1.26157483,  1.24185584,  1.3389332 , -0.58269175, -0.1995326 ,
       -0.23638456, -0.20544893,  0.86762188,  0.33787696, -1.02710429,
        1.32326315,  0.36843254])

In [59]:
b = np.random.randn(12)

In [60]:
b

array([-0.11885742,  0.35662502, -0.68127899, -1.39865885,  0.14615008,
       -1.80752092,  0.59070249, -1.44933707,  0.62325415, -1.08096924,
        0.22535051,  1.36861283])

In [63]:
np.maximum(a,b)

array([-0.11885742,  1.24185584,  1.3389332 , -0.58269175,  0.14615008,
       -0.23638456,  0.59070249,  0.86762188,  0.62325415, -1.02710429,
        1.32326315,  1.36861283])

In [83]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob','Will', 'Joe', 'Joe'])
names
idx = np.unique(names, return_index=True)
idx

(array(['Bob', 'Joe', 'Will'], dtype='<U4'), array([0, 1, 2]))

In [84]:
 a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
result

array([1, 2, 3, 4])

In [97]:
 sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray
C = np.delete(sampleArray, 1, 1)
newColumn = np.array([[10,10,10]])
C = np.insert(C,1,newColumn,axis=1)
C

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [100]:
 x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [104]:
 arr2d_1 = np.random.random((20,20))
arr2d_1
np.cumsum(arr2d_1)

array([1.43488409e-01, 2.26793143e-01, 4.68039806e-01, 1.29034251e+00,
       2.03436088e+00, 2.99679267e+00, 3.07921401e+00, 3.17428753e+00,
       3.58492799e+00, 4.56107777e+00, 4.77125039e+00, 5.19370613e+00,
       5.78048558e+00, 6.04873452e+00, 6.84998830e+00, 7.43216530e+00,
       8.07401542e+00, 8.92664369e+00, 9.03530454e+00, 9.65257840e+00,
       1.05409880e+01, 1.07509734e+01, 1.08403643e+01, 1.12722693e+01,
       1.18488637e+01, 1.24531158e+01, 1.27452308e+01, 1.30792959e+01,
       1.34211365e+01, 1.37091605e+01, 1.43840419e+01, 1.49992877e+01,
       1.53226954e+01, 1.57613471e+01, 1.59780982e+01, 1.63059089e+01,
       1.70946690e+01, 1.76700330e+01, 1.82073298e+01, 1.86309777e+01,
       1.93105424e+01, 1.93337501e+01, 2.01221824e+01, 2.02871296e+01,
       2.04425927e+01, 2.10225171e+01, 2.17511746e+01, 2.24251325e+01,
       2.31385125e+01, 2.40290340e+01, 2.48771080e+01, 2.55245316e+01,
       2.60558436e+01, 2.69507945e+01, 2.71497977e+01, 2.79432656e+01,
      